### ISSUE TITLE
How to Resolve "no main manifest attribute" Issue?

### ISSUE THREAD

**Issue by jwmarr87** [aslamanver/jar-builder#6] opened 2020-05-23 15:50 UTC
This may be related to Joel's issue.  I built the jar file (via running your extension in VS Code) and tried to run the jar file in a cmd window (Windows 10) using "java -jar [my jar file]".  

I received the follow error "no main manifest attribute, in [my jar file]". Please advise.

**Comment by javatlacati** [comment] 2020-06-26 15:56
Yes, it's a duplicate of https://github.com/aslamanver/jar-builder/issues/5

**Comment by aslamanver** [comment] 2020-06-28 03:37
This is because of the MANIFEST.MF file was not there, you can refer the below link to get the runnable Jar file, this is not the part of the Jar conversation.

https://stackoverflow.com/questions/9689793/cant-execute-jar-file-no-main-manifest-attribute

**Closed as completed by aslamanver** 2020-06-28 03:37 UTC
