### ISSUE TITLE
Don't know how to execute the jar file

### ISSUE THREAD

**Issue by UsrBinLuna** [aslamanver/jar-builder#9] opened 2020-08-17 17:01 UTC
Hi, I was testing your VSCode extension for building jar files from Java code, I built my code, used the command
``` java -jar cs.jar ```
In the VSCode Powershell command line, but it outputs
``` no main manifest attribute, in cs.jar ```
Any help please?
[Here the code if it's needed]
``` 
public class cs {

    public static void main(String[] args)
    {
//Conditional statements
        boolean isRainy = false;
        boolean hasUmbrella = false;
        
        if (isRainy == true && hasUmbrella == true) {
            System.out.println("Take your umbrella");
        } else if (isRainy == true || hasUmbrella == true) {
            System.out.println("Is it either raining, or you have an umbrella, or both");
        } else {
            System.out.println("It is not raining");
        }
    }
} 
```

**Comment by touchoftech** [comment] 2021-03-18 16:39
Since nobody else helped you, you probably faced the same issue I had when I used this plugin.  It's probably not the right way to get around this, but here's my 2 cents.

This is a simple program, and mine was too.  Jar-builder creates a META-INF/MANIFEST.MF file, but it doesn't include the Main-Class directive.  You can manually add it by opening your jar file up in something like WinRar.  Double click the manifest.mf file and it will open in your text editor.  Then add the following line at the bottom.
`Main-Class: cs`
Save the file and WinRar will ask you if you want to replace it in the jar file.  click yes.

You will probably get this error next:
`Error: Could not find or load main class cs
Caused by: java.lang.ClassNotFoundException: cs`

It may have been set up wrong, but for me jar-builder didn't actually compile my java files.  I had to open a command prompt and run
`javac .\cs.java` 
This compiled the cs.java into cs.class
Then if you go back into VScode and run jar-builder, the .class file will be included in the jar. Of course when you do that you'll have to go edit the manifest file again.  

Do this and your command will now execute as desired.

**Comment by aslamanver** [comment] 2021-03-22 19:11
JAR builder does not include your main class file, you can do it manually once the jar file is created. 

You need to refer the answer https://stackoverflow.com/questions/9689793/cant-execute-jar-file-no-main-manifest-attribute

**Closed as completed by aslamanver** 2021-03-22 19:11 UTC
